In [129]:
import json 
import pandas as pd

#load json object
with open('base/justica_estadual/processos-tjac/processos-tjac_1.json') as f:
    d = json.load(f)

### Movimento

In [130]:
pd.options.display.max_rows = 50

In [131]:
movimento = pd.json_normalize(data=d, record_path='movimento', meta=['millisInsercao', 'siglaTribunal', 'grau'])

In [132]:
movimento.head(10)

,tipoResponsavelMovimento,dataHora,tipoDecisao,movimentoNacional.codigoNacional,movimentoLocal.codigoMovimento,movimentoLocal.codigoPaiNacional,orgaoJulgador.nomeOrgao,orgaoJulgador.codigoMunicipioIBGE,orgaoJulgador.codigoOrgao,orgaoJulgador.instancia,millisInsercao,siglaTribunal,grau
0,1.0,20111222120000,0.0,246.0,NaN,NaN,NaN,NaN,NaN,NaN,1598672941539,TJAC,JE
1,0.0,20111219120000,0.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,1598672941539,TJAC,JE
2,1.0,20111213120000,0.0,463.0,NaN,NaN,NaN,NaN,NaN,NaN,1598672941539,TJAC,JE
3,NaN,20110919120000,NaN,NaN,50047.0,970.0,Vara Cível,1200302.0,8153.0,ORIG,1598672941539,TJAC,JE
4,0.0,20110919120000,0.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,1598672941539,TJAC,JE
5,0.0,20110920120000,0.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,1598672941539,TJAC,JE
6,0.0,00110920120000,0.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,1598672941539,TJAC,JE
7,1.0,20190116101915,0.0,132.0,NaN,NaN,NaN,NaN,NaN,NaN,1600348653544,TJAC,G1
8,1.0,20190116101911,0.0,454.0,NaN,NaN,NaN,NaN,NaN,NaN,1600348653544,TJAC,G1
9,0.0,20180911163140,0.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,1600348653544,TJAC,G1

In [135]:
movimento.shape

(50269, 13)

### Dados Básicos

In [118]:
dados_basicos = pd.json_normalize(data=d, record_path='dadosBasicos')

In [119]:
dados_basicos.head()

                  0
0           assunto
1            numero
2   dataAjuizamento
3  classeProcessual
4       nivelSigilo

In [120]:
dados_basicos.shape

(62778, 1)

### Outro opção

In [121]:
teste = pd.DataFrame.from_records(d, columns=["dadosBasicos", "movimento"])

In [125]:
teste.head()

,assunto,numero,dataAjuizamento,classeProcessual,nivelSigilo,orgaoJulgador,codigoLocalidade,competencia,totalAssuntos,valorCausa,procEl,dscSistema,tamanhoProcesso,dadosBasicos,movimento
0,"[{'principal': False, 'codigoNacional': 10959}]",00000641719898140200,625802400000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...",[{'movimentoNacional': {'codigoNacional': 246}...
1,"[{'principal': False, 'codigoNacional': 10959}]",00001467219948140200,777783600000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,0.0,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '2', 'movimentoLoc..."
2,"[{'principal': False, 'codigoNacional': 10959}]",00001761019948140200,783223200000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,0.0,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '2', 'movimentoLoc..."
3,"[{'principal': False, 'codigoNacional': 10959}]",00001585219958140200,806727600000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...",[{'movimentoNacional': {'codigoNacional': 246}...
4,"[{'principal': False, 'codigoNacional': 10959}]",00000716219968140200,824439600000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'movimentoLocal': {'codigoMovimento': 10921,..."

In [134]:
teste.shape

(7800, 15)

In [123]:
teste = (
    teste["dadosBasicos"]
    .apply(pd.Series)
    .merge(teste, left_index=True, right_index = True)
)

In [126]:
teste.head()

,assunto,numero,dataAjuizamento,classeProcessual,nivelSigilo,orgaoJulgador,codigoLocalidade,competencia,totalAssuntos,valorCausa,procEl,dscSistema,tamanhoProcesso,dadosBasicos,movimento
0,"[{'principal': False, 'codigoNacional': 10959}]",00000641719898140200,625802400000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...",[{'movimentoNacional': {'codigoNacional': 246}...
1,"[{'principal': False, 'codigoNacional': 10959}]",00001467219948140200,777783600000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,0.0,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '2', 'movimentoLoc..."
2,"[{'principal': False, 'codigoNacional': 10959}]",00001761019948140200,783223200000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,0.0,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '2', 'movimentoLoc..."
3,"[{'principal': False, 'codigoNacional': 10959}]",00001585219958140200,806727600000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...",[{'movimentoNacional': {'codigoNacional': 246}...
4,"[{'principal': False, 'codigoNacional': 10959}]",00000716219968140200,824439600000,12376,0,{'nomeOrgao': 'VARA ÚNICA DA JUSTIÇA MILITAR D...,572,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'movimentoLocal': {'codigoMovimento': 10921,..."