In [45]:
import json 
import pandas as pd

#load json object
with open('base/justica_eleitoral/processos-tre-ac/processos-tre-ac_3.json') as f:
    d = json.load(f)

### Movimento

In [86]:
movimento = pd.json_normalize(data=d, record_path='movimento', meta=['millisInsercao', 'siglaTribunal', 'grau'])

In [87]:
movimento.head()

,identificadorMovimento,tipoResponsavelMovimento,dataHora,movimentoNacional.codigoNacional,orgaoJulgador.nomeOrgao,orgaoJulgador.codigoMunicipioIBGE,orgaoJulgador.codigoOrgao,orgaoJulgador.instancia,tipoDecisao,millisInsercao,siglaTribunal,grau
0,80352,0.0,20200318073900,26,Gabinete do Presidente,1200401,78480,ORIG,NaN,1599677363520,TRE-AC,G2
1,80353,0.0,20200318074500,581,Gabinete do Presidente,1200401,78480,ORIG,NaN,1599677363520,TRE-AC,G2
2,80354,0.0,20200318074900,51,Gabinete do Presidente,1200401,78480,ORIG,NaN,1599677363520,TRE-AC,G2
3,80355,0.0,20200318074900,132,Gabinete do Presidente,1200401,78480,ORIG,NaN,1599677363520,TRE-AC,G2
4,2615,0.0,20200319074000,51,5 ZE - CARTÓRIO ELEITORAL DA 5ª ZONA,1200609,16030,ORIG,NaN,1599677422672,TRE-AC,G1

In [88]:
movimento.shape

(28014, 12)

### Dados Básicos

In [89]:
dados_basicos = pd.json_normalize(data=d, record_path='dadosBasicos')

In [90]:
dados_basicos.head()

                 0
0          assunto
1       dscSistema
2  tamanhoProcesso
3           numero
4           procEl

In [91]:
dados_basicos.shape

(23976, 1)

### Outro opção

In [92]:
teste = pd.DataFrame.from_records(d, columns=["dadosBasicos", "movimento"])

In [93]:
teste

,dadosBasicos,movimento
0,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '80352', 'tipoResp..."
1,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '2615', 'tipoRespo..."
2,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '402299', 'tipoRes..."
3,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '80349', 'tipoResp..."
4,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '397706', 'tipoRes..."
...,...,...
1993,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441469', 'tipoRes..."
1994,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441455', 'tipoRes..."
1995,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441480', 'tipoRes..."
1996,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441439', 'tipoRes..."
1997,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441444', 'tipoRes..."

In [94]:
teste = (
    teste["dadosBasicos"]
    .apply(pd.Series)
    .merge(teste, left_index=True, right_index = True)
)

In [60]:
teste

,assunto,dscSistema,tamanhoProcesso,numero,procEl,dataAjuizamento,totalAssuntos,classeProcessual,nivelSigilo,orgaoJulgador,...,89,90,91,92,93,94,95,96,dadosBasicos,movimento
0,"[{'principal': False, 'codigoNacional': 11572}]",1,-1,06000244520206010000,1,20200318000000,1,11544,0,"{'nomeOrgao': 'Gabinete do Presidente', 'codig...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '80352', 'tipoResp..."
1,"[{'principal': False, 'codigoNacional': 11575}]",1,-1,06000139820206010005,1,20200318000000,1,12549,0,{'nomeOrgao': '5 ZE - CARTÓRIO ELEITORAL DA 5ª...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '2615', 'tipoRespo..."
2,"[{'principal': False, 'codigoNacional': 12360}]",1,-1,06000253020206010000,1,20200318000000,1,1298,0,"{'nomeOrgao': 'Gabinete do Presidente', 'codig...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '402299', 'tipoRes..."
3,"[{'principal': False, 'codigoNacional': 11778}]",1,-1,06000607820206010003,1,20200318053100,1,12559,0,{'nomeOrgao': 'Gabinete do Corregedor Regional...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '80349', 'tipoResp..."
4,"[{'principal': False, 'codigoNacional': 12602}]",1,-1,06000250320206010009,1,20200319000000,1,241,0,{'nomeOrgao': '1 ZE - CARTÓRIO ELEITORAL DA 1ª...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '397706', 'tipoRes..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,"[{'principal': False, 'codigoNacional': 11638}...",1,-1,06001844620206010008,1,20200923221900,2,11532,0,{'nomeOrgao': '8 ZE - CARTÓRIO ELEITORAL DA 8ª...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441469', 'tipoRes..."
1994,"[{'principal': False, 'codigoNacional': 11638}...",1,-1,06001836120206010008,1,20200923221900,2,11532,0,{'nomeOrgao': '8 ZE - CARTÓRIO ELEITORAL DA 8ª...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441455', 'tipoRes..."
1995,"[{'principal': False, 'codigoNacional': 11638}...",1,-1,06001861620206010008,1,20200923221900,2,11532,0,{'nomeOrgao': '8 ZE - CARTÓRIO ELEITORAL DA 8ª...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441480', 'tipoRes..."
1996,"[{'principal': False, 'codigoNacional': 11618}...",1,-1,06001800920206010008,1,20200923221900,2,11532,0,{'nomeOrgao': '8 ZE - CARTÓRIO ELEITORAL DA 8ª...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441439', 'tipoRes..."
1997,"[{'principal': False, 'codigoNacional': 11618}...",1,-1,06001827620206010008,1,20200923221900,2,11532,0,{'nomeOrgao': '8 ZE - CARTÓRIO ELEITORAL DA 8ª...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'assunto': [{'principal': False, 'codigoNacio...","[{'identificadorMovimento': '441444', 'tipoRes..."